In [2]:
import torch

### 2.3.1 标量

In [2]:
x = torch.tensor(3.6)
y = torch.tensor(2.0)

In [3]:
x, y

(tensor(3.6000), tensor(2.))

In [4]:
x + y, x - y, x * y, x / y, x ** y

(tensor(5.6000),
 tensor(1.6000),
 tensor(7.2000),
 tensor(1.8000),
 tensor(12.9600))

### 2.3.2 向量

In [5]:
x = torch.arange(4)

In [11]:
x1 = x.reshape(-1, 1)

In [12]:
x1.shape

torch.Size([4, 1])

In [14]:
x1[2]

tensor([2])

In [15]:
len(x)

4

In [16]:
len(x1)

4

### 2.3.3 矩阵

In [17]:
A = torch.arange(20).reshape(4, 5)

In [18]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [19]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [20]:
A.T.shape

torch.Size([5, 4])

In [22]:
A[0, 1]

tensor(1)

In [23]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])

In [24]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [25]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4 张量

In [26]:
X = torch.arange(24).reshape(2, 4, 3)

In [27]:
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

### 2.3.5 张量算法的基本性质

In [28]:
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [29]:
Y = X.clone()

In [34]:
Y + X, Y * X, (Y * X).shape

(tensor([[[ 0,  2,  4],
          [ 6,  8, 10],
          [12, 14, 16],
          [18, 20, 22]],
 
         [[24, 26, 28],
          [30, 32, 34],
          [36, 38, 40],
          [42, 44, 46]]]),
 tensor([[[  0,   1,   4],
          [  9,  16,  25],
          [ 36,  49,  64],
          [ 81, 100, 121]],
 
         [[144, 169, 196],
          [225, 256, 289],
          [324, 361, 400],
          [441, 484, 529]]]),
 torch.Size([2, 4, 3]))

### 2.3.6 降维

In [35]:
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [37]:
X.sum().shape

torch.Size([])

In [40]:
X.sum(axis=0), X.sum(axis=1)

(tensor([[12, 14, 16],
         [18, 20, 22],
         [24, 26, 28],
         [30, 32, 34]]),
 tensor([[18, 22, 26],
         [66, 70, 74]]))

In [39]:
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [3]:
X = torch.arange(12, dtype=float).reshape(3, 4)

In [47]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [49]:
X.mean(), X.sum() / X.numel()

(tensor(5.5000, dtype=torch.float64), tensor(5.5000, dtype=torch.float64))

In [51]:
X.mean(axis=1), X.sum(axis=1) / X.shape[1]

(tensor([1.5000, 5.5000, 9.5000], dtype=torch.float64),
 tensor([1.5000, 5.5000, 9.5000], dtype=torch.float64))

#### 非降维求和

In [6]:
S = X.sum(axis=0, keepdims=True)

In [8]:
S, S.shape

(tensor([[12., 15., 18., 21.]], dtype=torch.float64), torch.Size([1, 4]))

In [9]:
S1 = X.sum(axis=1, keepdims=True)

In [10]:
S1, S1.shape

(tensor([[ 6.],
         [22.],
         [38.]], dtype=torch.float64),
 torch.Size([3, 1]))

In [11]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

### 2.3.7 点积（Dot Product）

In [12]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [26]:
X = torch.arange(6, dtype=torch.float32)

In [27]:
Y = torch.ones_like(X) * 0.5

In [28]:
X, Y

(tensor([0., 1., 2., 3., 4., 5.]),
 tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000]))

In [29]:
torch.dot(X, Y)

tensor(7.5000)

In [30]:
X * Y, (X * Y).sum()

(tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000]), tensor(7.5000))

### 2.3.8 矩阵-向量积

In [31]:
A = torch.arange(20).reshape(5, 4)

In [36]:
A, A.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 torch.Size([5, 4]))

In [33]:
X = torch.arange(4)

In [37]:
X, X.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [38]:
torch.mv(A, X)

tensor([ 14,  38,  62,  86, 110])

In [39]:
_.shape

torch.Size([5])

In [40]:
A[0] * X

tensor([0, 1, 4, 9])

In [41]:
_.sum()

tensor(14)

### 2.3.9 矩阵-矩阵乘法

In [42]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [44]:
B = torch.arange(12).reshape(4, 3)

In [45]:
B

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [46]:
torch.mm(A, B)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

In [47]:
_.shape

torch.Size([5, 3])

In [50]:
A[0] * B[:, 0]

tensor([ 0,  3, 12, 27])

In [51]:
_.sum()

tensor(42)

In [52]:
A[1] * B[:, 1]

tensor([ 4, 20, 42, 70])

In [53]:
_.sum()

tensor(136)

### 2.3.10 范数

In [54]:
u = torch.tensor([3.0, 4])

In [57]:
torch.norm(u)  # L2范数

tensor(5.)

In [56]:
(u ** 2).sum() ** 0.5

tensor(5.)

In [59]:
# L1范数
u1 = torch.tensor([-3.0, 4])

In [60]:
torch.abs(u1).sum()

tensor(7.)

In [63]:
# 矩阵的范数
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

In [64]:
torch.norm(A)

tensor(9.5394)

In [66]:
(A ** 2).sum() ** 0.5

tensor(9.5394)