In [1]:
import torch  # torch 火炬

### 2.2.1 pytorch张量（tensor）

In [2]:
x = torch.arange(15)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
type(x)

torch.Tensor

In [5]:
x.shape  # 张量的形状

torch.Size([15])

In [6]:
x.reshape(3, 5)  # 改变张量的形状

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [8]:
x.numel()  # 张量的元素总数

15

#### 创建一个全0的张量

In [11]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

#### 创建一个全1的张量

In [12]:
torch.ones(3, 6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

#### 创建一个元素符合正态分布的随机张量

In [13]:
torch.randn(3, 7)

tensor([[-1.2684,  1.0679, -0.4450, -0.4613, -0.7750,  1.0775,  0.9476],
        [-0.8435, -1.2638,  0.3740, -1.5040,  0.3525, -0.4228, -0.9788],
        [-1.2436,  1.3120,  0.5624, -0.1862, -0.5008,  0.4394,  1.3265]])

#### 自定义一个张量

In [14]:
torch.tensor([[1, 2, 3], [7, 8, 9], [100, 101, 102]])

tensor([[  1,   2,   3],
        [  7,   8,   9],
        [100, 101, 102]])

In [15]:
_.shape

torch.Size([3, 3])

### 2.1.2 张量的运算

In [16]:
x = torch.tensor([1.0, 2.1, 3.6])
y = torch.tensor([100, 200, 300])

In [17]:
x + y

tensor([101.0000, 202.1000, 303.6000])

In [18]:
x - y

tensor([ -99.0000, -197.9000, -296.4000])

In [19]:
x * y

tensor([ 100.0000,  420.0000, 1080.0000])

In [20]:
y / x

tensor([100.0000,  95.2381,  83.3333])

In [22]:
y ** x

tensor([1.0000e+02, 6.7946e+04, 8.2725e+08])

In [24]:
torch.exp(x)  # e的指数

tensor([ 2.7183,  8.1662, 36.5982])

#### 张量的拼接

In [25]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)

In [26]:
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [31]:
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [32]:
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [33]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [36]:
x.sum()

tensor(66.)

In [37]:
y.sum()

tensor(30.)

### 2.1.3 广播机制

In [38]:
a = torch.arange(3).reshape(3, 1)

In [40]:
b = torch.arange(2).reshape(1, 2)

In [42]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [43]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [44]:
a1 = torch.tensor([[0, 0], [1, 1], [2, 2]])
b1 = torch.tensor([[0, 1], [0, 1], [0, 1]])

In [46]:
a1 + b1 == a + b

tensor([[True, True],
        [True, True],
        [True, True]])

### 2.1.4 索引和切片

In [47]:
x = torch.arange(24).reshape(3, 2, 4)

In [50]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [51]:
x[0]

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [52]:
x[-1]

tensor([[16, 17, 18, 19],
        [20, 21, 22, 23]])

In [53]:
x[:, 0]

tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]])

In [54]:
x[:2, 0, 1:3]

tensor([[ 1,  2],
        [ 9, 10]])

In [55]:
x[-1, 0, -1] = 100

In [56]:
x

tensor([[[  0,   1,   2,   3],
         [  4,   5,   6,   7]],

        [[  8,   9,  10,  11],
         [ 12,  13,  14,  15]],

        [[ 16,  17,  18, 100],
         [ 20,  21,  22,  23]]])

### 2.1.5 内存操作

In [57]:
before_id = id(x)

In [58]:
before_id

1977427280896

In [59]:
x = x * 0.5

In [62]:
id(x) == before_id

False

In [63]:
z = torch.zeros_like(x)

In [65]:
id(z)

1977427096448

In [66]:
z[:] = x + torch.ones_like(x)

In [67]:
z

tensor([[[ 1.0000,  1.5000,  2.0000,  2.5000],
         [ 3.0000,  3.5000,  4.0000,  4.5000]],

        [[ 5.0000,  5.5000,  6.0000,  6.5000],
         [ 7.0000,  7.5000,  8.0000,  8.5000]],

        [[ 9.0000,  9.5000, 10.0000, 51.0000],
         [11.0000, 11.5000, 12.0000, 12.5000]]])

In [68]:
id(z)

1977427096448

In [69]:
z += x

In [70]:
z

tensor([[[  1.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.]],

        [[  9.,  10.,  11.,  12.],
         [ 13.,  14.,  15.,  16.]],

        [[ 17.,  18.,  19., 101.],
         [ 21.,  22.,  23.,  24.]]])

In [71]:
id(z)

1977427096448

### 2.1.6 tensor转为python对象

In [72]:
import numpy

In [73]:
a = numpy.arange(3)

In [74]:
a

array([0, 1, 2])

In [75]:
b = torch.arange(3)

In [76]:
b

tensor([0, 1, 2])

In [77]:
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [78]:
c = torch.tensor([11.9])

In [79]:
c, c.item(), float(c), int(c)

(tensor([11.9000]), 11.899999618530273, 11.899999618530273, 11)

In [80]:
str(c)

'tensor([11.9000])'