In [1]:
import numpy as np
import torch
from torch.utils import data

In [2]:
import d2l

### 3.3.1 生成数据集

In [3]:
true_w = torch.tensor([5.8, -11])
true_b = torch.tensor(7.7)

In [4]:
features, labels = d2l.synthetic_data(true_w, true_b, 10000)

### 3.3.2 读取数据集

In [5]:
for x, y in d2l.load_array((features, labels), 10):
    print(x)
    print(y)
    break

tensor([[ 1.4104, -0.5487],
        [-0.2974,  0.2460],
        [-0.3645,  1.0009],
        [ 0.7739,  0.0021],
        [ 0.0186, -0.2276],
        [-0.3259, -0.1638],
        [-0.0129, -0.9802],
        [ 1.8333,  0.0069],
        [-0.1960, -0.1108],
        [-0.0022,  0.7544]])
tensor([[21.9268],
        [ 3.2631],
        [-5.4330],
        [12.1726],
        [10.3139],
        [ 7.6213],
        [18.4024],
        [18.2847],
        [ 7.7805],
        [-0.6085]])


### 3.3.3 定义模型

In [6]:
from torch import nn

In [7]:
# 一个线性层，输入特征形状为2，输出现状为1
net = nn.Sequential(nn.Linear(2, 1))

### 3.3.4 初始化参数

In [8]:
net[0].weight.data.normal_(0, 0.01)

tensor([[0.0206, 0.0031]])

In [9]:
net[0].bias.data.fill_(0)

tensor([0.])

### 3.3.5 损失函数

In [10]:
loss = nn.MSELoss()  # 均方差损失函数

### 3.3.6 定义优化算法

In [11]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

### 3.3.7 训练

In [17]:
num_epochs = 3
data_iter = d2l.load_array((features, labels), 10)

In [18]:
for i in range(num_epochs):
    for X, y in data_iter:
        y_hat = net(X)
        l = loss(y_hat, y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f"第{i+1}轮，损失是：{l:f}")

第1轮，损失是：0.000102
第2轮，损失是：0.000102
第3轮，损失是：0.000101


In [20]:
true_w, net[0].weight.data

(tensor([  5.8000, -11.0000]), tensor([[  5.8001, -10.9998]]))

In [22]:
true_w - net[0].weight.data

tensor([[-0.0001, -0.0002]])

In [21]:
true_b, net[0].bias.data

(tensor(7.7000), tensor([7.7006]))

In [23]:
true_b - net[0].bias.data

tensor([-0.0006])