In [1]:
import torch

In [2]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
torch.arange(maxlen, dtype=torch.float32, device=X.device)

tensor([0., 1., 2.])

In [5]:
maxlen = X.size(1)
maxlen

3

In [7]:
torch.arange(maxlen, dtype=torch.float32, device=X.device)[None, :]

tensor([[0., 1., 2.]])

In [10]:
valid_len = torch.tensor([1, 2])
torch.arange(maxlen, dtype=torch.float32, device=X.device)[None, :] < valid_len[:, None]

tensor([[ True, False, False],
        [ True,  True, False]])

In [11]:
torch.tensor([1, 2])[:, None]

tensor([[1],
        [2]])