In [1]:
import torch

### 2.5.1 一个简单的例子

In [2]:
x = torch.arange(7.)

In [3]:
x.requires_grad_(True)

tensor([0., 1., 2., 3., 4., 5., 6.], requires_grad=True)

In [4]:
x.grad is None

True

In [5]:
y = 2 * torch.dot(x, x)

In [6]:
y

tensor(182., grad_fn=<MulBackward0>)

In [8]:
y.backward()

In [9]:
x.grad

tensor([ 0.,  4.,  8., 12., 16., 20., 24.])

In [10]:
x.grad == 4 * x

tensor([True, True, True, True, True, True, True])

In [11]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0.])

In [12]:
x.grad

tensor([0., 0., 0., 0., 0., 0., 0.])

In [13]:
y = x.sum()

In [14]:
y

tensor(21., grad_fn=<SumBackward0>)

In [15]:
y.backward()

In [16]:
x.grad

tensor([1., 1., 1., 1., 1., 1., 1.])

### 2.5.2 非标量变量的反向传播

In [17]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0.])

In [18]:
y = x * x

In [19]:
y.sum()

tensor(91., grad_fn=<SumBackward0>)

In [20]:
_.backward()

In [21]:
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12.])

### 2.5.3 导数的分离计算

In [22]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0.])

In [23]:
y = x * x

In [24]:
u = y.detach()

In [25]:
u

tensor([ 0.,  1.,  4.,  9., 16., 25., 36.])

In [26]:
z = u * x

In [27]:
z.sum().backward()

In [28]:
x.grad

tensor([ 0.,  1.,  4.,  9., 16., 25., 36.])

In [30]:
x.grad == u

tensor([True, True, True, True, True, True, True])

In [31]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0.])

In [32]:
y.sum().backward()

In [34]:
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12.])

In [35]:
2 * x

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12.], grad_fn=<MulBackward0>)

In [36]:
x.grad == 2 * x

tensor([True, True, True, True, True, True, True])

### 2.5.4 Python控制流的梯度计算

In [37]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [72]:
a = torch.randn(size=(), requires_grad=True)

In [73]:
a.grad is None, a

(True, tensor(0.4697, requires_grad=True))

In [74]:
d = f(a)

In [75]:
d.backward()

In [76]:
a.grad

tensor(4096.)

In [77]:
d / a

tensor(4096., grad_fn=<DivBackward0>)