In [1]:
import torch
from torch import nn

In [2]:
import sys
sys.path.insert(0, '..')
from common import d2l

#### 1. 填充

In [14]:
def comp_conv2d(conv2d, X):
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    return Y.reshape(Y.shape[2:])

In [11]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1)

In [15]:
X = torch.rand(size=(8, 8))
X

tensor([[0.7956, 0.8159, 0.0415, 0.4644, 0.6488, 0.4344, 0.9109, 0.6410],
        [0.4336, 0.5314, 0.7623, 0.8971, 0.5424, 0.1760, 0.2694, 0.9884],
        [0.4103, 0.9388, 0.6596, 0.3007, 0.0743, 0.8236, 0.1522, 0.1374],
        [0.9271, 0.3509, 0.5246, 0.1063, 0.7034, 0.1629, 0.3682, 0.7009],
        [0.4503, 0.9445, 0.3662, 0.9807, 0.8342, 0.6674, 0.3182, 0.4974],
        [0.1113, 0.1155, 0.7469, 0.3005, 0.4464, 0.6874, 0.9967, 0.8691],
        [0.5218, 0.9945, 0.1506, 0.9075, 0.9784, 0.8591, 0.5273, 0.7428],
        [0.5603, 0.5415, 0.5951, 0.9339, 0.0880, 0.7482, 0.5135, 0.3894]])

In [16]:
Y = comp_conv2d(conv2d, X)
Y, Y.shape

(tensor([[-0.5588, -0.3456, -0.2963, -0.6316, -0.5385, -0.4415, -0.4611, -0.3701],
         [-0.7734, -0.5445, -0.6773, -0.7851, -0.3333, -0.5348, -0.7926, -0.2839],
         [-0.8333, -0.8691, -0.6657, -0.3405, -0.3753, -0.4691, -0.4598, -0.4109],
         [-0.8442, -0.6970, -0.3943, -0.3629, -0.8079, -0.5375, -0.3799, -0.3681],
         [-0.7198, -0.4124, -0.4837, -0.7885, -0.5763, -0.3882, -0.7187, -0.5384],
         [-0.6037, -0.7306, -0.6767, -0.6865, -0.7693, -0.7722, -0.7362, -0.4198],
         [-0.6095, -0.7248, -0.5604, -0.8450, -0.7853, -0.7856, -0.7852, -0.3042],
         [-0.7887, -0.4031, -0.5176, -0.7174, -0.4220, -0.5127, -0.3748, -0.1447]],
        grad_fn=<ViewBackward0>),
 torch.Size([8, 8]))

#### 2. 步幅

In [17]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)

In [18]:
Y = comp_conv2d(conv2d, X)
Y, Y.shape

(tensor([[0.1331, 0.4155, 0.2503, 0.3474],
         [0.0721, 0.2925, 0.2184, 0.5206],
         [0.1040, 0.0971, 0.2541, 0.4782],
         [0.1407, 0.4404, 0.5819, 0.4704]], grad_fn=<ViewBackward0>),
 torch.Size([4, 4]))

In [25]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))

In [26]:
Y = comp_conv2d(conv2d, X)
Y, Y.shape

(tensor([[-0.1324, -0.2481],
         [-0.2125, -0.3611]], grad_fn=<ViewBackward0>),
 torch.Size([2, 2]))