In [1]:
import torch
from torch import nn

#### 1. 最大池化层和平均池化层

In [8]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [4]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
X

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [10]:
pool2d(X, (2, 2)), pool2d(X, (2, 2), 'avg')

(tensor([[4., 5.],
         [7., 8.]]),
 tensor([[2., 3.],
         [5., 6.]]))

#### 2. 池化层的填充和步幅

In [11]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [12]:
pool2d = nn.MaxPool2d((3, 3))

In [13]:
pool2d(X)

tensor([[[[10.]]]])

In [15]:
pool2d = nn.MaxPool2d((3, 3), padding=1)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [17]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [18]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

#### 3. 多通道输入池化

In [19]:
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [20]:
pool2d = nn.AvgPool2d(2)

In [21]:
pool2d(X)

tensor([[[[ 2.5000,  4.5000],
          [10.5000, 12.5000]],

         [[ 3.5000,  5.5000],
          [11.5000, 13.5000]]]])

In [22]:
_.shape, X.shape

(torch.Size([1, 2, 2, 2]), torch.Size([1, 2, 4, 4]))