### 1. 概览

In [1]:
import numpy as np

In [2]:
a = np.arange(15)

In [3]:
a = a.reshape(3, 5)

In [4]:
b = range(15)

In [5]:
b

range(0, 15)

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])

In [14]:
b

array([6, 7, 8])

In [15]:
type(b)

numpy.ndarray

### 2. 创建数组

In [16]:
a = np.array([2, 3, 4])

In [17]:
a

array([2, 3, 4])

In [18]:
a.dtype

dtype('int32')

In [19]:
b = np.array([1.2, 3.5, 5.1])

In [20]:
b.dtype

dtype('float64')

In [21]:
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [24]:
a = np.array([1, 2, 3, 4])

In [25]:
a

array([1, 2, 3, 4])

In [27]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [28]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [29]:
b.dtype

dtype('float64')

In [30]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [31]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [32]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [34]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
_.dtype

dtype('float64')

In [36]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [37]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### 3. 打印数组

In [41]:
a = np.arange(6)

In [42]:
print(a)

[0 1 2 3 4 5]


In [45]:
b = np.arange(12).reshape(4, 3)

In [46]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
c = np.arange(24).reshape(2, 3, 4)

In [49]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [51]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [52]:
np.set_printoptions(threshold=0)

### 4. 基本运算

In [54]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [55]:
c = a - b

In [56]:
c

array([20, 29, 38, 47])

In [57]:
b ** 2

array([0, 1, 4, 9])

In [58]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [59]:
a < 35

array([ True,  True, False, False])

In [60]:
_.dtype

dtype('bool')

In [62]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [63]:
A + B

array([[3, 1],
       [3, 5]])

In [64]:
A * B

array([[2, 0],
       [0, 4]])

In [65]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [66]:
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))

In [67]:
a, b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[0.35936925, 0.66720427, 0.17595374],
        [0.85597131, 0.6324036 , 0.50482868]]))

In [68]:
a *= 3

In [69]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [70]:
b += a

In [71]:
b

array([[3.35936925, 3.66720427, 3.17595374],
       [3.85597131, 3.6324036 , 3.50482868]])

In [72]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [75]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)

In [76]:
a, b

(array([1, 1, 1]), array([0.        , 1.57079633, 3.14159265]))

In [77]:
b.dtype.name

'float64'

In [78]:
c = a + b

In [79]:
c

array([1.        , 2.57079633, 4.14159265])

In [80]:
c.dtype.name

'float64'

In [81]:
d = np.exp(c * 1j)

In [82]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [83]:
d.dtype.name

'complex128'

In [84]:
a = np.random.random((2, 3))

In [85]:
a

array([[0.52018659, 0.20212413, 0.77360807],
       [0.92537815, 0.02493687, 0.41118213]])

In [86]:
a.sum()

2.857415940654433

In [87]:
a.min()

0.024936867668609586

In [88]:
a.max()

0.9253781475265602

In [89]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [91]:
b.min(axis=1)

array([0, 4, 8])

In [92]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### 5. 通用函数

In [93]:
B = np.arange(3)
B

array([0, 1, 2])

In [94]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [95]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [99]:
C = np.array([2., -1., 4.])

In [100]:
np.add(B, C)

array([2., 0., 6.])

In [98]:
_.mean()

0.8047378541243649

In [101]:
a = np.arange(10) ** 3

In [102]:
a

array([  0,   1,   8, ..., 343, 512, 729], dtype=int32)

In [103]:
a[2]

8

In [104]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [105]:
a[:6:2] = -1000

In [106]:
a[::-1]

array([  729,   512,   343, ..., -1000,     1, -1000], dtype=int32)

In [112]:
for i in a:
    print(i)
    print(i**(1/3.))
    # print(i)

-1000
nan
1
1.0
-1000
nan
27
3.0
-1000
nan
125
5.0
216
5.999999999999999
343
6.999999999999999
512
7.999999999999999
729
8.999999999999998


C:\Users\25639\AppData\Local\Temp\ipykernel_15944\955657838.py:3: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))


In [113]:
(-1000) ** (1/3.)

(5+8.660254037844384j)

In [115]:
def f(x, y):
    return 10 * x + y

In [116]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [117]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [118]:
b[2, 3]

23

In [119]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [120]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [121]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [122]:
b[-1]

array([40, 41, 42, 43])

In [123]:
b[1, ...]

array([10, 11, 12, 13])

In [124]:
b[..., 0]

array([ 0, 10, 20, 30, 40])

In [125]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [127]:
for element in b.flat:
    print(element, end=',')

0,1,2,3,10,11,12,13,20,21,22,23,30,31,32,33,40,41,42,43,

### 6. 形状操作

In [129]:
a = np.floor(10 * np.random.random((3, 4)))

In [130]:
a

array([[7., 4., 3., 9.],
       [8., 8., 3., 6.],
       [1., 0., 8., 6.]])

In [131]:
np.random.random((3, 4))

array([[0.86333331, 0.7290905 , 0.78346373, 0.06192432],
       [0.77467943, 0.00375306, 0.9355939 , 0.36672359],
       [0.08005772, 0.12013223, 0.55634036, 0.09281056]])

In [132]:
a.shape

(3, 4)

In [133]:
a.ravel()

array([7., 4., 3., ..., 0., 8., 6.])

In [134]:
a.shape = (6, 2)

In [135]:
a.transpose()

array([[7., 3., 8., 3., 1., 8.],
       [4., 9., 8., 6., 0., 6.]])

In [136]:
a

array([[7., 4.],
       [3., 9.],
       [8., 8.],
       [3., 6.],
       [1., 0.],
       [8., 6.]])

In [137]:
a.resize((2, 6))

In [138]:
a

array([[7., 4., 3., 9., 8., 8.],
       [3., 6., 1., 0., 8., 6.]])

#### 组合（stack）不同的数组

In [142]:
a = np.floor(10 * np.random.random((2, 2)))

In [143]:
a

array([[4., 9.],
       [7., 4.]])

In [144]:
b = np.floor(10 * np.random.random((2, 2)))
b

array([[4., 2.],
       [8., 0.]])

In [145]:
np.vstack((a, b))

array([[4., 9.],
       [7., 4.],
       [4., 2.],
       [8., 0.]])

In [146]:
np.hstack((a, b))

array([[4., 9., 4., 2.],
       [7., 4., 8., 0.]])

In [147]:
np.column_stack((a, b))

array([[4., 9., 4., 2.],
       [7., 4., 8., 0.]])

In [148]:
a = np.array([4., 2.])
b = np.array([2., 8.])

In [149]:
a, b

(array([4., 2.]), array([2., 8.]))

In [150]:
a[:, np.newaxis]

array([[4.],
       [2.]])

In [151]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 2.],
       [2., 8.]])

In [152]:
np.vstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4.],
       [2.],
       [2.],
       [8.]])

In [153]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [154]:
np.c_[1:4, 0, 4]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [155]:
a = np.floor(10 * np.random.random((2, 12)))

In [156]:
a

array([[9., 2., 1., ..., 3., 9., 9.],
       [8., 6., 6., ..., 5., 2., 6.]])

In [157]:
np.hsplit(a, 3)

[array([[9., 2., 1., 9.],
        [8., 6., 6., 3.]]),
 array([[5., 5., 0., 9.],
        [1., 6., 4., 3.]]),
 array([[6., 3., 9., 9.],
        [1., 5., 2., 6.]])]

In [158]:
np.hsplit(a, (3, 4))

[array([[9., 2., 1.],
        [8., 6., 6.]]),
 array([[9.],
        [3.]]),
 array([[5., 5., 0., ..., 3., 9., 9.],
        [1., 6., 4., ..., 5., 2., 6.]])]

In [159]:
np.vsplit(a, 2)

[array([[9., 2., 1., ..., 3., 9., 9.]]),
 array([[8., 6., 6., ..., 5., 2., 6.]])]

In [160]:
a = np.arange(12)

In [161]:
b = a

In [162]:
b is a

True

In [163]:
b.shape = 3, 4

In [164]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
a.shape

(3, 4)

In [167]:
def f(x):
    print(id(x))

In [168]:
id(a)

2035541818896

In [169]:
f(a)

2035541818896


In [170]:
f(b)

2035541818896


#### 视图和浅复制

In [171]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
c = a.view()

In [173]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [174]:
c is a

False

In [175]:
c.base is a

True

In [176]:
c.base

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
c.flags.owndata

False

In [178]:
a.flags.owndata

True

In [179]:
c.shape = 2, 6

In [180]:
a.shape

(3, 4)

In [181]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [182]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
c[0, 4] = 1235

In [185]:
c

array([[   0,    1,    2,    3, 1235,    5],
       [   6,    7,    8,    9,   10,   11]])

In [186]:
a

array([[   0,    1,    2,    3],
       [1235,    5,    6,    7],
       [   8,    9,   10,   11]])

In [187]:
s = a[:, 1:3]

In [188]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [189]:
s[:] = 10

In [190]:
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [191]:
a

array([[   0,   10,   10,    3],
       [1235,   10,   10,    7],
       [   8,   10,   10,   11]])

In [192]:
d = a.copy()

In [193]:
d

array([[   0,   10,   10,    3],
       [1235,   10,   10,    7],
       [   8,   10,   10,   11]])

In [194]:
d is a

False

In [195]:
d.base is a

False

In [196]:
d[0, 0] = 9999

In [197]:
d, a

(array([[9999,   10,   10,    3],
        [1235,   10,   10,    7],
        [   8,   10,   10,   11]]),
 array([[   0,   10,   10,    3],
        [1235,   10,   10,    7],
        [   8,   10,   10,   11]]))