### 1. 广播法则

### 2. 花哨的索引和索引技巧

In [1]:
import numpy as np

In [2]:
a = np.arange(12) ** 2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [4]:
i = np.array([1, 1, 3, 8, 5])

In [5]:
a[i]

array([ 1,  1,  9, 64, 25])

In [6]:
j = np.array([[3, 4], [9, 7]])

In [7]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [8]:
palette = np.array([
    [0, 0, 0],
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255],
    [255, 255, 255]
])

In [9]:
image = np.array([
    [0, 1, 2, 0],
    [0, 3, 4, 0]
])

In [10]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [11]:
a = np.arange(12).reshape(3, 4)

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
i = np.array([[0, 1], [1, 2]])

In [14]:
j = np.array([[2, 1], [3, 3]])

In [15]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [16]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [17]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [18]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [19]:
l = [i, j]

In [20]:
a[l]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
time = np.linspace(20, 145, 5)
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [22]:
data = np.sin(np.arange(20)).reshape(5, 4)

In [23]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [24]:
ind = data.argmax(axis=0)

In [25]:
ind

array([2, 0, 3, 1], dtype=int64)

In [26]:
time_max = time[ind]

In [27]:
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [28]:
data_max = data[ind, range(data.shape[1])]

In [29]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [30]:
all(data_max == data.max(axis=0))

True

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a[[1, 3, 4]] = 0

In [34]:
a

array([0, 0, 2, 0, 0])

In [35]:
a = np.arange(5)

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a[[0, 0, 2]] = [1, 2, 3]

In [38]:
a

array([2, 1, 3, 3, 4])

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
a[[0, 0, 2]] += 1

In [41]:
a

array([1, 1, 3, 3, 4])